# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build images
  jobs:  
  - job: Build
    displayName: Build images
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build WebApp image (Frontend)
      inputs:
        command: build
        dockerfile: 'Sources/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@3
      displayName: Build WebApp image (Authentication Service)
      inputs:
        command: build
        dockerfile: 'Sources/Dockerfile-Auth'
        tags: |
          $(tag)
    - task: Docker@4
      displayName: Build WebApp image (Machinedata Service)
      inputs:
        command: build
        dockerfile: 'Sources/Dockerfile-MachineData'
        tags: |
          $(tag)