version: '3' 
services: 
  webapp: 
    build:
      context: ./Sources
      dockerfile: DockerFile
    environment: 
      - AuthServiceUrl=http://localhost:5001/api/auth 
      - MachineDataServiceUrl=http://localhost:5005/api/machinedata 
    ports: 
      - "5000:5000" 
    depends_on: 
      - authservice
      - machinedataservice
  
  authservice: 
    build:
      context: ./Sources
      dockerfile: DockerFile-Auth
    container_name: authservice
    environment: 
      - ConnectionString=Server=sqlserver;Database=MachineDataDatabase;UserId=SA;Pwd=p@ssword
    ports: 
      - "5001:5001" 
    networks:
       - workshopnet
    depends_on: 
      - sqlserver

  machinedataservice: 
    build:
      context: ./Sources
      dockerfile: DockerFile-MachineData
    container_name: machinedataservice
    environment: 
      - ConnectionString=Server=sqlserver;Database=MachineDataDatabase;UserId=SA;Pwd=p@ssword 
    ports: 
      - "5005:5005" 
    networks:
       - workshopnet
    depends_on: 
      - sqlserver 

  sqlserver: 
    image: microsoft/mssql-server-linux:latest 
    container_name: sqlserver
    environment: 
      - SA_PASSWORD=p@ssw0rd 
      - ACCEPT_EULA=Y 
    volumes:
       - D:\sqlstoragewin:/var/opt/mssql
    networks:
       - workshopnet
    ports: 
      - "1433:1433"

volumes:
  db-data:

networks:
  workshopnet:
