# create a debug build of all projects used by app server
# for production readiness use docker_composer.yml
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.1-sdk AS build-ms-machinedata
WORKDIR /src
COPY ["Source/MicroServices/MachineData/JoergIsAGeek.Workshop.Enterprise.ServiceLayer.MachineData/JoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj", "."]
RUN dotnet restore "JoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "JoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj" -c Release -o /app

FROM build-ms-machinedata AS publish-ms-machinedata
RUN dotnet publish "JoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj" -c Release -o /app

FROM base AS final-ms-machinedata
WORKDIR /app
EXPOSE 5005
COPY --from=publish-ms-machinedata /app .
ENTRYPOINT ["dotnet", "JoergIsAGeek.Workshop.Enterprise.ServiceLayer.dll"]