# create a debug build of all projects used by app server
# for production readiness use docker_composer.yml
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM  mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build-ms-machinedata
WORKDIR /src
COPY . .

RUN dotnet restore "MicroServices/MachineData/ServiceLayer/JoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj"
RUN dotnet build "MicroServices/MachineData/ServiceLayer/JoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj" -c Release -o /app/build

FROM build-ms-machinedata AS publish-ms-machinedata
RUN dotnet publish "MicroServices/MachineData/ServiceLayerJoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj" -c Release -o /app/publish

FROM base AS final-ms-machinedata
WORKDIR /app
EXPOSE 5005
COPY --from=publish-ms-machinedata /app/publish .
ENTRYPOINT ["dotnet", "JoergIsAGeek.Workshop.Enterprise.ServiceLayer.dll"]

