/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";

export const id: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    serializedName: "id",
    type: {
      name: "Number"
    }
  }
};
export const value: msRest.OperationURLParameter = {
  parameterPath: "value",
  mapper: {
    required: true,
    serializedName: "value",
    type: {
      name: "Number"
    }
  }
};
