/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";
import * as Models from "./models";

const packageName = "";
const packageVersion = "";

export class MachineDataAPIContext extends msRest.ServiceClient {

  /**
   * Initializes a new instance of the MachineDataAPIContext class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.MachineDataAPIOptions) {

    if (!options) {
      options = {};
    }

    super(undefined, options);

    this.baseUri = options.baseUri || this.baseUri || "http://localhost";
    this.requestContentType = "application/json; charset=utf-8";

    this.addUserAgentInfo(`${packageName}/${packageVersion}`);
  }
}
