FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["JoergIsAGeek.Workshop.Enterprise.ServiceLayer.Authentication/JoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj", "."]
COPY ["JoergIsAGeek.Workshop.Enterprise.BusinessLogicLayer.Authentication/JoergIsAGeek.Workshop.Enterprise.BusinessLogicLayer.csproj", "."]
COPY ["JoergIsAGeek.Workshop.Enterprise.DataTransferObjectsAuthentication/JoergIsAGeek.Workshop.Enterprise.DataTransferObjects.csproj", "."]
RUN dotnet restore "JoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "JoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "JoergIsAGeek.Workshop.Enterprise.ServiceLayer.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
EXPOSE 5001
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "JoergIsAGeek.Workshop.Enterprise.ServiceLayer.dll"]