// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JoergIsAGeek.Workshop.Enterprise.WebFrontEnd.ServiceProxy.AuthenticationService.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class IdentityResult
    {
        /// <summary>
        /// Initializes a new instance of the IdentityResult class.
        /// </summary>
        public IdentityResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IdentityResult class.
        /// </summary>
        public IdentityResult(bool? succeeded = default(bool?), IList<IdentityError> errors = default(IList<IdentityError>))
        {
            Succeeded = succeeded;
            Errors = errors;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "succeeded")]
        public bool? Succeeded { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IList<IdentityError> Errors { get; private set; }

    }
}
